# config.yaml

scheduler:
  interval_seconds: 10       # how often to run check_endpoints
  max_500_response_threshold: 3       # number of 5xx responses before sending Discord alert
  cleanup_after_days: 30     # days after which to delete old EndpointStatus rows

endpoints:
  - url: "https://example.com"
  - url: "https://httpbin.org/status/200"
  - url: "https://httpbin.org/status/503"
  - url: "https://httpbin.org/status/418"
