# default.yaml

scheduler:
  interval_seconds: 10       # how often to run check_endpoints
  max_500_response_threshold: 3       # number of 500+ responses before sending Discord alert
  cleanup_after_days: 0.001     # days after which to delete old EndpointStatus rows

endpoints:
  add:
    - url: "https://example.com"
    - url: "https://httpbin.org/status/200"
    - url: "https://httpbin.org/status/503"
  
  delete:
    - url: "https://httpbin.org/status/300"
